### ISSUE TITLE
Bug in DMX_examples_SX/free_fall_dt.py related to resample_integrator.py

### ISSUE THREAD

**Issue by EnricoMingo** [ADVRHumanoids/Horizon_old#2]
After porting the ```DMX_examples_SX/free_fall_dt.py``` i got the following error related to the ```resample_integrator``` after the optimal solution is found

```Traceback (most recent call last):
  File "/home/enrico/advr-superbuild/external/Horizon/python/DMS_examples_SX/free_fall_dt.py", line 198, in <module>
    X_res = resample_integrator(X, Qddot, dt_hist, dt, dae)
  File "/home/enrico/advr-superbuild/external/Horizon/python/utils/resample_integrator.py", line 75, in resample_integrator
    X_res[0:nx, 0] = X[0]
  File "/home/enrico/.local/lib/python2.7/site-packages/casadi/casadi.py", line 9084, in __setitem__
    return self.set(val, False, s[0], s[1])
  File "/home/enrico/.local/lib/python2.7/site-packages/casadi/casadi.py", line 8011, in set
    return _casadi.SX_set(self, *args)
RuntimeError: .../casadi/core/slice.cpp:83: Assertion "stop<=len" failed:
Slice (start=0, stop=1, step=1) out of bounds with supplied length of 0```

**Comment by matteoparigi** [comment]
When I run ```DMX_examples_SX/free_fall_dt.py``` from my pc  I get:

`EXIT: Optimal Solution Found.`
with
`Number of Iterations....: 216`

but I do not get any error afterwards
